### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by MinscyBubu** [crskycode/DDWSystemTool#1]
could you update this tool to make compatible with this vn?

https://vndb.org/v800

**Comment by crskycode** [comment]
So, what problem did you encounter?

**Comment by MinscyBubu** [comment]
This

![imagen](https://user-images.githubusercontent.com/88146930/140677517-eec2e8a1-81d9-4634-8c71-339c8c181854.png)

**Comment by crskycode** [comment]
You should use a HexEditor to confirm the file header.

**Comment by MinscyBubu** [comment]
This?
![imagen](https://user-images.githubusercontent.com/88146930/140678143-989c04af-b0ce-4004-80a2-bca577f465b5.png)

Btw, this is the file (remove the .txt extension):
[b080.hxb.txt](https://github.com/crskycode/DDWSystemTool/files/7494012/b080.hxb.txt)

**Comment by crskycode** [comment]
Uh, this file from an very old version of the engine. This tool can't compatible.
